import type { Language } from '../../global/types';

// טקסטים של עמוד המנוי. במילון מקומי (ולא ב-i18n הגלובלי) כי הם שייכים רק
// לפיצ'ר הזה. שלוש השפות חייבות להכיל בדיוק אותם מפתחות (נאכף בטיפוס).
const he = {
  pageTitle: 'ניהול מנוי',
  summaryValidUntil: 'המנוי יהיה פעיל עד',
  confirmTitle: 'ביצעתם את ההעברה?',
  confirmBody: 'נדווח שהעברתם ₪{amount} עם הקוד הזה. אם עוד לא שילמתם, אפשר לחזור ולשלם.',
  confirmYes: 'כן, שילמתי',
  confirmNo: 'עוד לא',
  faqTitle: 'שאלות נפוצות',
  faq1q: 'מה קורה אחרי שאני משלם?',
  faq1a: 'לוחצים "שילמתי", אנחנו בודקים שההעברה הגיעה ומפעילים את המנוי. תקבלו התראה ברגע שזה קורה.',
  faq2q: 'טעיתי בסכום או שכחתי את הקוד',
  faq2a: 'לא נורא. פנו אלינו במייל עם קוד ההפניה ופרטי ההעברה ונסדר את זה.',
  faq3q: 'האם יש חיוב אוטומטי?',
  faq3a: 'לא. זה תשלום חד-פעמי לתקופה שבחרתם, והמנוי פשוט מסתיים בסופה.',
  helpLink: 'צריכים עזרה? שלחו לנו מייל',
  welcomeTitle: 'ברוכים הבאים ל-Pro!',
  welcomeBody: 'קיבלתם {n} חודשי Pro במתנה. הכל פתוח, בלי הגבלות ובלי כרטיס אשראי.',
  welcomeCta: 'מתחילים',
  welcomeDetails: 'פרטי המנוי',
  perksTitle: 'מה מקבלים ב-Pro',
  perkLists: 'רשימות ללא הגבלה',
  perkGroups: 'קבוצות בלי מגבלת חברים',
  perkAi: 'עוזר AI בלי הגבלה',
  perkPrice: 'השוואות מחיר בלי הגבלה',
  trustNoAuto: 'בלי חיוב אוטומטי',
  trustManual: 'כל תשלום מאומת אישית',
  trustExtend: 'הארכה בלי לאבד ימים',
  payBank: 'העברה בנקאית',
  bankName: 'בנק',
  bankBranch: 'סניף',
  bankAccount: 'מספר חשבון',
  copyAmount: 'העתקת סכום',
  stepChoose: 'בחירה',
  stepPay: 'תשלום',
  stepDone: 'אישור',
  welcomeBack: 'חזרתם מהתשלום? אם ההעברה בוצעה, לחצו "שילמתי"',
  activatedTitle: 'המנוי הופעל!',
  activatedBody: 'תודה שהצטרפתם. כל התכונות פתוחות עכשיו ללא הגבלה.',
  activatedCta: 'מעולה',
  bannerTrialSoon: 'הניסיון מסתיים בעוד {n} ימים',
  bannerTrialToday: 'הניסיון מסתיים היום',
  bannerTrialSoonSub: 'ממשיכים ליהנות מ-Pro בכמה לחיצות',
  bannerTrialEnded: 'הניסיון הסתיים',
  bannerTrialEndedSub: 'חוזרים ל-Pro בכמה לחיצות',
  bannerCta: 'להמשך',
  upgradeModalPrice: 'תשלום חד-פעמי, בלי חיוב אוטומטי',
  from: 'החל מ-',
  trialBadge: 'מתנה',
  trialTitle: 'Pro במתנה בשבילך',
  trialSub: 'נהנים מהכל ללא הגבלה עד',
  trialEndedBadge: 'הניסיון הסתיים',
  trialEndedTitle: 'תקופת הניסיון הסתיימה',
  trialEndedSub: 'חזרתם לתוכנית החינמית. אפשר להמשיך ל-Pro בכל רגע.',
  trialKeepCta: 'ממשיכים ליהנות מ-Pro',
  trialKeepNote: 'ההמשך מתווסף אחרי סוף תקופת המתנה, בלי לאבד אף יום.',
  welcomeToast: 'ברוכים הבאים! קיבלתם {n} חודשי Pro במתנה',
  loadError: 'לא הצלחנו לטעון את פרטי המנוי',
  retry: 'נסו שוב',

  proBadge: 'Pro',
  freeBadge: 'חינמי',
  heroFreeTitle: 'Smart Basket Pro',
  heroFreeSub: 'הכל ללא הגבלה, בלי חיוב אוטומטי',
  heroProTitle: 'המנוי שלך פעיל',
  heroPermanentSub: 'מנוי Pro קבוע, ללא תאריך תפוגה',
  heroActiveUntil: 'פעיל עד',
  daysLeft: 'ימים נותרו',
  dayLeft: 'יום אחד נותר',
  expiresToday: 'מסתיים היום',
  expiringSoon: 'המנוי עומד להסתיים - כדאי להאריך',

  usageTitle: 'השימוש שלך היום',
  usageAi: 'שאלות לעוזר AI',
  usagePrice: 'השוואות מחיר',
  usageResets: 'המונים מתאפסים בכל יום',
  usageOf: 'מתוך',
  limitLists: 'רשימות בבעלותך',
  limitMembers: 'חברים בקבוצה',

  compareTitle: 'מה מקבלים ב-Pro',
  compareFree: 'חינמי',
  comparePro: 'Pro',
  cmpLists: 'רשימות',
  cmpMembers: 'חברים בקבוצה',
  cmpAi: 'שאלות AI ביום',
  cmpPrice: 'השוואות מחיר ביום',
  unlimited: 'ללא הגבלה',

  planTitle: 'בחרו תקופה',
  month1: 'חודש',
  month3: '3 חודשים',
  month12: 'שנה',
  perMonth: 'לחודש',
  total: 'סה״כ',
  saveBadge: 'חיסכון של',
  noAutoRenew: 'תשלום חד-פעמי. אין חיוב אוטומטי ואין חידוש שקט, המנוי פשוט מסתיים בתום התקופה.',
  upgradeCta: 'המשך לתשלום',
  renewCta: 'הארכת המנוי',
  renewNote: 'ההארכה מתווספת לסוף התקופה הנוכחית, בלי לאבד ימים.',

  payTitle: 'תשלום',
  payStep1Link: 'שלמו דרך האפליקציה',
  payStep1Bank: 'העבירו לחשבון',
  payStep2: 'כתבו בהערה את הקוד',
  payStep3: 'סיימתם להעביר?',
  payAmount: 'סכום לתשלום',
  payFor: 'עבור',
  payMethod: 'אמצעי תשלום',
  payBit: 'ביט',
  payPaybox: 'PayBox',
  payScan: 'סרקו את הקוד עם אפליקציית הבנק או ביט',
  payOpenBit: 'פתיחה בביט',
  payOpenPaybox: 'פתיחה ב-PayBox',
  payReference: 'קוד הפניה להערה',
  payReferenceHint: 'כתבו אותו בהערת ההעברה כדי שנזהה אתכם מהר',
  copy: 'העתק',
  copied: 'הועתק',
  paidCta: 'שילמתי',
  paidHint: 'לחצו רק אחרי שההעברה בוצעה. אנחנו בודקים אותה ידנית ומפעילים את המנוי.',
  cancelRequest: 'ביטול הבקשה',
  changePlan: 'שינוי תקופה',
  payUnavailableTitle: 'התשלום עדיין לא מוגדר',
  payUnavailableBody: 'כרגע אפשר לשדרג רק בפנייה אלינו במייל. נחזור אליכם עם פרטי התשלום.',
  contactUs: 'שליחת מייל',
  paymentDetailsNote: 'פרטי התשלום מגיעים ישירות מהשרת. אל תשלמו לפרטים אחרים.',

  reportedTitle: 'התשלום בבדיקה',
  reportedBody: 'קיבלנו את הדיווח. ברגע שנראה את ההעברה המנוי יופעל ותקבלו התראה.',
  reportedRef: 'קוד הפניה',
  reportedSince: 'דווח',
  rejectedTitle: 'לא הצלחנו לאמת את התשלום',
  rejectedBody: 'לא מצאנו את ההעברה. אפשר לנסות שוב או לפנות אלינו.',

  historyTitle: 'היסטוריית בקשות',
  statusPending: 'ממתין לתשלום',
  statusReported: 'בבדיקה',
  statusApproved: 'אושר',
  statusRejected: 'נדחה',
  statusCancelled: 'בוטל',

  errorGeneric: 'משהו השתבש, נסו שוב',
  errorAlreadyReported: 'כבר יש תשלום שממתין לאישור',
  cancelledToast: 'הבקשה בוטלה',
  reportedToast: 'הדיווח נשלח, נעדכן ברגע שהמנוי יופעל',
} as const;

export type SubscriptionStrings = { [K in keyof typeof he]: string };

const en: SubscriptionStrings = {
  pageTitle: 'Manage subscription',
  summaryValidUntil: 'Your plan will be active until',
  confirmTitle: 'Did you make the transfer?',
  confirmBody: 'We will record that you transferred ₪{amount} with this code. If you have not paid yet, go back and pay first.',
  confirmYes: 'Yes, I paid',
  confirmNo: 'Not yet',
  faqTitle: 'Common questions',
  faq1q: 'What happens after I pay?',
  faq1a: 'You tap "I paid", we check the transfer arrived and activate your plan. You get a notification when it happens.',
  faq2q: 'I sent the wrong amount or forgot the code',
  faq2a: 'No problem. Email us with the reference code and transfer details and we will sort it out.',
  faq3q: 'Is there automatic billing?',
  faq3a: 'No. It is a one-time payment for the period you chose, and the plan simply ends after it.',
  helpLink: 'Need help? Email us',
  welcomeTitle: 'Welcome to Pro!',
  welcomeBody: 'You got {n} months of Pro as a gift. Everything unlocked, no limits and no credit card.',
  welcomeCta: 'Let us start',
  welcomeDetails: 'Subscription details',
  perksTitle: 'What you get with Pro',
  perkLists: 'Unlimited lists',
  perkGroups: 'Groups with no member cap',
  perkAi: 'Unlimited AI assistant',
  perkPrice: 'Unlimited price comparisons',
  trustNoAuto: 'No automatic billing',
  trustManual: 'Every payment verified personally',
  trustExtend: 'Extend without losing days',
  payBank: 'Bank transfer',
  bankName: 'Bank',
  bankBranch: 'Branch',
  bankAccount: 'Account number',
  copyAmount: 'Copy amount',
  stepChoose: 'Choose',
  stepPay: 'Pay',
  stepDone: 'Confirm',
  welcomeBack: 'Back from paying? If the transfer is done, tap "I paid"',
  activatedTitle: 'Your plan is active!',
  activatedBody: 'Thanks for joining. Every feature is now unlocked with no limits.',
  activatedCta: 'Great',
  bannerTrialSoon: 'Your trial ends in {n} days',
  bannerTrialToday: 'Your trial ends today',
  bannerTrialSoonSub: 'Keep enjoying Pro in a few taps',
  bannerTrialEnded: 'Your trial has ended',
  bannerTrialEndedSub: 'Get Pro back in a few taps',
  bannerCta: 'Continue',
  upgradeModalPrice: 'One-time payment, no automatic billing',
  from: 'From ',
  trialBadge: 'Gift',
  trialTitle: 'Pro is on us',
  trialSub: 'Enjoy everything unlimited until',
  trialEndedBadge: 'Trial ended',
  trialEndedTitle: 'Your trial has ended',
  trialEndedSub: 'You are back on the free plan. You can continue with Pro at any time.',
  trialKeepCta: 'Keep enjoying Pro',
  trialKeepNote: 'Your extension starts after the gift period ends, no days lost.',
  welcomeToast: 'Welcome! You got {n} months of Pro as a gift',
  loadError: 'Could not load your subscription',
  retry: 'Try again',

  proBadge: 'Pro',
  freeBadge: 'Free',
  heroFreeTitle: 'Smart Basket Pro',
  heroFreeSub: 'Everything unlimited, no automatic billing',
  heroProTitle: 'Your subscription is active',
  heroPermanentSub: 'Permanent Pro, no expiry date',
  heroActiveUntil: 'Active until',
  daysLeft: 'days left',
  dayLeft: '1 day left',
  expiresToday: 'Ends today',
  expiringSoon: 'Your subscription is ending soon - consider extending',

  usageTitle: 'Your usage today',
  usageAi: 'AI assistant questions',
  usagePrice: 'Price comparisons',
  usageResets: 'Counters reset every day',
  usageOf: 'of',
  limitLists: 'Lists you own',
  limitMembers: 'Members per group',

  compareTitle: 'What you get with Pro',
  compareFree: 'Free',
  comparePro: 'Pro',
  cmpLists: 'Lists',
  cmpMembers: 'Group members',
  cmpAi: 'AI questions per day',
  cmpPrice: 'Price comparisons per day',
  unlimited: 'Unlimited',

  planTitle: 'Choose a period',
  month1: '1 month',
  month3: '3 months',
  month12: '1 year',
  perMonth: '/ month',
  total: 'Total',
  saveBadge: 'Save',
  noAutoRenew: 'One-time payment. No automatic billing and no silent renewal, the subscription simply ends after the period.',
  upgradeCta: 'Continue to payment',
  renewCta: 'Extend subscription',
  renewNote: 'The extension is added after your current period, so you lose no days.',

  payTitle: 'Payment',
  payStep1Link: 'Pay with the app',
  payStep1Bank: 'Transfer to the account',
  payStep2: 'Write the code in the note',
  payStep3: 'Done transferring?',
  payAmount: 'Amount to pay',
  payFor: 'for',
  payMethod: 'Payment method',
  payBit: 'Bit',
  payPaybox: 'PayBox',
  payScan: 'Scan the code with your bank app or Bit',
  payOpenBit: 'Open in Bit',
  payOpenPaybox: 'Open in PayBox',
  payReference: 'Reference code for the note',
  payReferenceHint: 'Write it in the transfer note so we can match you quickly',
  copy: 'Copy',
  copied: 'Copied',
  paidCta: 'I paid',
  paidHint: 'Tap only after the transfer is done. We check it manually and activate your plan.',
  cancelRequest: 'Cancel request',
  changePlan: 'Change period',
  payUnavailableTitle: 'Payment is not set up yet',
  payUnavailableBody: 'For now you can upgrade only by emailing us. We will reply with payment details.',
  contactUs: 'Send email',
  paymentDetailsNote: 'Payment details come directly from our server. Do not pay any other details.',

  reportedTitle: 'Payment under review',
  reportedBody: 'We received your report. Once we see the transfer your plan is activated and you get a notification.',
  reportedRef: 'Reference code',
  reportedSince: 'Reported',
  rejectedTitle: 'We could not verify the payment',
  rejectedBody: 'We did not find the transfer. You can try again or contact us.',

  historyTitle: 'Request history',
  statusPending: 'Awaiting payment',
  statusReported: 'Under review',
  statusApproved: 'Approved',
  statusRejected: 'Rejected',
  statusCancelled: 'Cancelled',

  errorGeneric: 'Something went wrong, try again',
  errorAlreadyReported: 'You already have a payment awaiting approval',
  cancelledToast: 'Request cancelled',
  reportedToast: 'Report sent, we will update you once your plan is active',
};

const ru: SubscriptionStrings = {
  pageTitle: 'Управление подпиской',
  summaryValidUntil: 'Подписка будет активна до',
  confirmTitle: 'Вы выполнили перевод?',
  confirmBody: 'Мы отметим, что вы перевели ₪{amount} с этим кодом. Если ещё не оплатили, вернитесь и оплатите.',
  confirmYes: 'Да, я оплатил',
  confirmNo: 'Ещё нет',
  faqTitle: 'Частые вопросы',
  faq1q: 'Что будет после оплаты?',
  faq1a: 'Нажмите «Я оплатил», мы проверим поступление и активируем подписку. Придёт уведомление.',
  faq2q: 'Я ошибся в сумме или забыл код',
  faq2a: 'Ничего страшного. Напишите нам на почту с кодом и данными перевода, и мы всё решим.',
  faq3q: 'Есть ли автосписание?',
  faq3a: 'Нет. Это разовый платёж за выбранный срок, подписка просто заканчивается.',
  helpLink: 'Нужна помощь? Напишите нам',
  welcomeTitle: 'Добро пожаловать в Pro!',
  welcomeBody: 'Вам подарено {n} мес. Pro. Всё открыто, без лимитов и без банковской карты.',
  welcomeCta: 'Начнём',
  welcomeDetails: 'Детали подписки',
  perksTitle: 'Что даёт Pro',
  perkLists: 'Неограниченные списки',
  perkGroups: 'Группы без лимита участников',
  perkAi: 'AI-помощник без лимита',
  perkPrice: 'Сравнение цен без лимита',
  trustNoAuto: 'Без автосписаний',
  trustManual: 'Каждый платёж проверяется лично',
  trustExtend: 'Продление без потери дней',
  payBank: 'Банковский перевод',
  bankName: 'Банк',
  bankBranch: 'Отделение',
  bankAccount: 'Номер счёта',
  copyAmount: 'Копировать сумму',
  stepChoose: 'Выбор',
  stepPay: 'Оплата',
  stepDone: 'Подтверждение',
  welcomeBack: 'Вернулись после оплаты? Если перевод выполнен, нажмите «Я оплатил»',
  activatedTitle: 'Подписка активирована!',
  activatedBody: 'Спасибо, что с нами. Все функции теперь без ограничений.',
  activatedCta: 'Отлично',
  bannerTrialSoon: 'Пробный период закончится через {n} дн.',
  bannerTrialToday: 'Пробный период заканчивается сегодня',
  bannerTrialSoonSub: 'Продолжите с Pro в пару нажатий',
  bannerTrialEnded: 'Пробный период закончился',
  bannerTrialEndedSub: 'Вернитесь на Pro в пару нажатий',
  bannerCta: 'Продолжить',
  upgradeModalPrice: 'Разовый платёж, без автосписаний',
  from: 'От ',
  trialBadge: 'Подарок',
  trialTitle: 'Pro в подарок',
  trialSub: 'Пользуйтесь всем без ограничений до',
  trialEndedBadge: 'Пробный период закончился',
  trialEndedTitle: 'Пробный период закончился',
  trialEndedSub: 'Вы вернулись на бесплатный план. Перейти на Pro можно в любой момент.',
  trialKeepCta: 'Продолжить с Pro',
  trialKeepNote: 'Продление начнётся после подарочного периода, ни один день не теряется.',
  welcomeToast: 'Добро пожаловать! Вам подарено {n} мес. Pro',
  loadError: 'Не удалось загрузить данные подписки',
  retry: 'Повторить',

  proBadge: 'Pro',
  freeBadge: 'Бесплатно',
  heroFreeTitle: 'Smart Basket Pro',
  heroFreeSub: 'Всё без ограничений, без автоматических списаний',
  heroProTitle: 'Ваша подписка активна',
  heroPermanentSub: 'Постоянный Pro, без срока окончания',
  heroActiveUntil: 'Действует до',
  daysLeft: 'дн. осталось',
  dayLeft: 'остался 1 день',
  expiresToday: 'Заканчивается сегодня',
  expiringSoon: 'Подписка скоро закончится, рекомендуем продлить',

  usageTitle: 'Ваше использование сегодня',
  usageAi: 'Вопросы AI-помощнику',
  usagePrice: 'Сравнения цен',
  usageResets: 'Счётчики сбрасываются каждый день',
  usageOf: 'из',
  limitLists: 'Ваши списки',
  limitMembers: 'Участников в группе',

  compareTitle: 'Что даёт Pro',
  compareFree: 'Бесплатно',
  comparePro: 'Pro',
  cmpLists: 'Списки',
  cmpMembers: 'Участники группы',
  cmpAi: 'Вопросов AI в день',
  cmpPrice: 'Сравнений цен в день',
  unlimited: 'Без ограничений',

  planTitle: 'Выберите срок',
  month1: '1 месяц',
  month3: '3 месяца',
  month12: '1 год',
  perMonth: '/ мес.',
  total: 'Итого',
  saveBadge: 'Экономия',
  noAutoRenew: 'Разовый платёж. Без автосписаний и скрытого продления, подписка просто заканчивается по истечении срока.',
  upgradeCta: 'Перейти к оплате',
  renewCta: 'Продлить подписку',
  renewNote: 'Продление добавляется к концу текущего периода, дни не теряются.',

  payTitle: 'Оплата',
  payStep1Link: 'Оплатите через приложение',
  payStep1Bank: 'Переведите на счёт',
  payStep2: 'Укажите код в комментарии',
  payStep3: 'Перевод выполнен?',
  payAmount: 'Сумма к оплате',
  payFor: 'за',
  payMethod: 'Способ оплаты',
  payBit: 'Bit',
  payPaybox: 'PayBox',
  payScan: 'Отсканируйте код в приложении банка или Bit',
  payOpenBit: 'Открыть в Bit',
  payOpenPaybox: 'Открыть в PayBox',
  payReference: 'Код для комментария',
  payReferenceHint: 'Укажите его в комментарии к переводу, чтобы мы быстро вас нашли',
  copy: 'Копировать',
  copied: 'Скопировано',
  paidCta: 'Я оплатил',
  paidHint: 'Нажимайте только после перевода. Мы проверяем вручную и активируем подписку.',
  cancelRequest: 'Отменить запрос',
  changePlan: 'Сменить срок',
  payUnavailableTitle: 'Оплата ещё не настроена',
  payUnavailableBody: 'Пока улучшить план можно только написав нам на почту. Мы пришлём реквизиты.',
  contactUs: 'Написать письмо',
  paymentDetailsNote: 'Реквизиты приходят напрямую с нашего сервера. Не платите по другим реквизитам.',

  reportedTitle: 'Оплата на проверке',
  reportedBody: 'Мы получили ваше сообщение. Как только увидим перевод, подписка будет активирована, и вы получите уведомление.',
  reportedRef: 'Код',
  reportedSince: 'Отправлено',
  rejectedTitle: 'Не удалось подтвердить оплату',
  rejectedBody: 'Мы не нашли перевод. Можно попробовать снова или связаться с нами.',

  historyTitle: 'История запросов',
  statusPending: 'Ожидает оплаты',
  statusReported: 'На проверке',
  statusApproved: 'Подтверждено',
  statusRejected: 'Отклонено',
  statusCancelled: 'Отменено',

  errorGeneric: 'Что-то пошло не так, попробуйте ещё раз',
  errorAlreadyReported: 'У вас уже есть платёж на подтверждении',
  cancelledToast: 'Запрос отменён',
  reportedToast: 'Сообщение отправлено, сообщим, когда подписка будет активна',
};

const DICTS: Record<Language, SubscriptionStrings> = { he, en, ru };

export const getSubscriptionStrings = (lang: Language): SubscriptionStrings => DICTS[lang] ?? he;
