import type { Language } from '../../global/types';

// טקסטים של עמוד המנוי. במילון מקומי (ולא ב-i18n הגלובלי) כי הם שייכים רק
// לפיצ'ר הזה. שלוש השפות חייבות להכיל בדיוק אותם מפתחות (נאכף בטיפוס).
const he = {
  pageTitle: 'ניהול מנוי',
  loadError: 'לא הצלחנו לטעון את פרטי המנוי',
  retry: 'נסו שוב',

  perksTitle: 'מה מקבלים ב-Pro',
  perkLists: 'רשימות ללא הגבלה',
  perkGroups: 'קבוצות בלי מגבלת חברים',
  perkAi: 'עוזר AI בלי הגבלה',
  perkPrice: 'השוואות מחיר בלי הגבלה',

  welcomeTitle: 'ברוכים הבאים ל-Pro!',
  welcomeBody: 'קיבלתם {n} חודשי Pro במתנה. הכל פתוח, בלי הגבלות ובלי כרטיס אשראי.',
  welcomeCta: 'מתחילים',
  welcomeDetails: 'פרטי המנוי',
  welcomeWhatYouGet: 'מה זה נותן לך',
  paidWelcomeBadge: 'Pro פעיל',
  paidWelcomeTitle: 'המנוי הופעל!',
  paidWelcomeBody: 'תודה שבחרת ב-Pro. המנוי פעיל עד {date}.',
  paidWelcomeBodyPermanent: 'תודה שבחרת ב-Pro. המנוי פעיל ללא תאריך תפוגה.',
  manualWelcomeTitle: 'Pro הופעל!',
  manualWelcomeBody: 'הצוות שלנו הפעיל עבורך Pro, פעיל עד {date}.',
  manualWelcomeBodyPermanent: 'הצוות שלנו הפעיל עבורך Pro, ללא תאריך תפוגה.',

  bannerTrialSoon: 'הניסיון מסתיים בעוד {n} ימים',
  bannerTrialToday: 'הניסיון מסתיים היום',
  bannerTrialSoonSub: 'ממשיכים ליהנות מ-Pro בכמה לחיצות',
  bannerTrialEnded: 'הניסיון הסתיים',
  bannerTrialEndedSub: 'חוזרים ל-Pro בכמה לחיצות',
  bannerCta: 'להמשך',

  proBadge: 'Pro',
  freeBadge: 'חינמי',
  trialBadge: 'מתנה',
  trialTitle: 'Pro במתנה בשבילך',
  trialSub: 'נהנים מהכל ללא הגבלה עד',
  trialEndedBadge: 'הניסיון הסתיים',
  trialEndedTitle: 'תקופת הניסיון הסתיימה',
  trialEndedSub: 'חזרתם לתוכנית החינמית. אפשר להמשיך ל-Pro בכל רגע.',
  heroFreeTitle: 'Smart Basket Pro',
  heroFreeSub: 'הכל ללא הגבלה, בכל המכשירים שלך',
  heroProTitle: 'המנוי שלך פעיל',
  heroPermanentSub: 'מנוי Pro קבוע, ללא תאריך תפוגה',
  heroActiveUntil: 'פעיל עד',
  heroRenewsOn: 'מתחדש אוטומטית ב',
  daysLeft: 'ימים נותרו',
  dayLeft: 'יום אחד נותר',
  expiresToday: 'מסתיים היום',
  expiringSoon: 'המנוי עומד להסתיים',
  sourceStore: 'מנוי דרך חנות האפליקציות',
  sourceGranted: 'הופעל על ידי הצוות',

  compareTitle: 'מה כלול בכל תוכנית',
  compareFree: 'חינמי',
  comparePro: 'Pro',
  compareLists: 'רשימות בבעלותך',
  compareGroups: 'חברים בקבוצה',
  compareAi: 'בקשות AI ביום',
  comparePriceChecks: 'השוואות מחיר ביום',
  compareUnlimited: 'ללא הגבלה',
  usageResets: 'המונים מתאפסים בכל יום',

  appOnlyTitle: 'מצטרפים ל-Pro באפליקציה',
  appOnlyBody: 'התשלום מתבצע בבטחה דרך App Store או Google Play. מורידים את Smart Basket, מתחברים לאותו חשבון, ו-Pro פעיל בכל המכשירים, גם כאן.',
  appOnlySoon: 'האפליקציה תהיה זמינה בחנויות בקרוב.',
  appOnlyRenewTitle: 'המשך המנוי נעשה באפליקציה',
  storeManageTitle: 'המנוי שלך מנוהל בחנות',
  storeManageBody: 'לשינוי או לביטול, פתחו בטלפון את הגדרות המנויים של App Store או Google Play.',
  supportPrompt: 'שאלות על המנוי?',
  supportCta: 'כתבו לנו',
};

export type SubscriptionStrings = { [K in keyof typeof he]: string };

const en: SubscriptionStrings = {
  pageTitle: 'Subscription',
  loadError: 'Could not load your subscription',
  retry: 'Try again',

  perksTitle: 'What you get with Pro',
  perkLists: 'Unlimited lists',
  perkGroups: 'Groups with no member limit',
  perkAi: 'Unlimited AI assistant',
  perkPrice: 'Unlimited price comparisons',

  welcomeTitle: 'Welcome to Pro!',
  welcomeBody: 'You got {n} months of Pro as a gift. Everything is unlocked, no limits and no credit card.',
  welcomeCta: "Let's go",
  welcomeDetails: 'Subscription details',
  welcomeWhatYouGet: 'What it gives you',
  paidWelcomeBadge: 'Pro active',
  paidWelcomeTitle: 'Subscription activated!',
  paidWelcomeBody: 'Thanks for choosing Pro. Your subscription is active until {date}.',
  paidWelcomeBodyPermanent: 'Thanks for choosing Pro. Your subscription has no expiry date.',
  manualWelcomeTitle: 'Pro activated!',
  manualWelcomeBody: 'Our team activated Pro for you, active until {date}.',
  manualWelcomeBodyPermanent: 'Our team activated Pro for you, with no expiry date.',

  bannerTrialSoon: 'Your trial ends in {n} days',
  bannerTrialToday: 'Your trial ends today',
  bannerTrialSoonSub: 'Keep enjoying Pro in a few taps',
  bannerTrialEnded: 'Your trial has ended',
  bannerTrialEndedSub: 'Get back to Pro in a few taps',
  bannerCta: 'Continue',

  proBadge: 'Pro',
  freeBadge: 'Free',
  trialBadge: 'Gift',
  trialTitle: 'Pro, on us',
  trialSub: 'Enjoy everything without limits until',
  trialEndedBadge: 'Trial ended',
  trialEndedTitle: 'Your trial has ended',
  trialEndedSub: 'You are back on the free plan. You can continue with Pro anytime.',
  heroFreeTitle: 'Smart Basket Pro',
  heroFreeSub: 'Everything unlimited, on all your devices',
  heroProTitle: 'Your subscription is active',
  heroPermanentSub: 'Permanent Pro, no expiry date',
  heroActiveUntil: 'Active until',
  heroRenewsOn: 'Renews automatically on',
  daysLeft: 'days left',
  dayLeft: '1 day left',
  expiresToday: 'Ends today',
  expiringSoon: 'Your subscription is ending soon',
  sourceStore: 'Subscribed through the app store',
  sourceGranted: 'Activated by our team',

  compareTitle: "What's included in each plan",
  compareFree: 'Free',
  comparePro: 'Pro',
  compareLists: 'Lists you own',
  compareGroups: 'Group members',
  compareAi: 'AI requests per day',
  comparePriceChecks: 'Price comparisons per day',
  compareUnlimited: 'Unlimited',
  usageResets: 'Counters reset every day',

  appOnlyTitle: 'Get Pro in the app',
  appOnlyBody: 'Payment is handled securely by the App Store or Google Play. Download Smart Basket, sign in to the same account, and Pro works on all your devices, including here.',
  appOnlySoon: 'The app will be available in the stores soon.',
  appOnlyRenewTitle: 'Continue your subscription in the app',
  storeManageTitle: 'Your subscription is managed by the store',
  storeManageBody: 'To change or cancel it, open the subscription settings of the App Store or Google Play on your phone.',
  supportPrompt: 'Questions about your subscription?',
  supportCta: 'Write to us',
};

const ru: SubscriptionStrings = {
  pageTitle: 'Подписка',
  loadError: 'Не удалось загрузить данные подписки',
  retry: 'Повторить',

  perksTitle: 'Что даёт Pro',
  perkLists: 'Списки без ограничений',
  perkGroups: 'Группы без ограничения участников',
  perkAi: 'AI помощник без ограничений',
  perkPrice: 'Сравнение цен без ограничений',

  welcomeTitle: 'Добро пожаловать в Pro!',
  welcomeBody: 'Вы получили {n} мес. Pro в подарок. Всё открыто, без ограничений и без карты.',
  welcomeCta: 'Начать',
  welcomeDetails: 'Детали подписки',
  welcomeWhatYouGet: 'Что это даёт',
  paidWelcomeBadge: 'Pro активен',
  paidWelcomeTitle: 'Подписка активирована!',
  paidWelcomeBody: 'Спасибо, что выбрали Pro. Подписка активна до {date}.',
  paidWelcomeBodyPermanent: 'Спасибо, что выбрали Pro. Подписка без срока окончания.',
  manualWelcomeTitle: 'Pro активирован!',
  manualWelcomeBody: 'Наша команда активировала для вас Pro до {date}.',
  manualWelcomeBodyPermanent: 'Наша команда активировала для вас Pro без срока окончания.',

  bannerTrialSoon: 'Пробный период закончится через {n} дн.',
  bannerTrialToday: 'Пробный период заканчивается сегодня',
  bannerTrialSoonSub: 'Продолжайте пользоваться Pro в пару касаний',
  bannerTrialEnded: 'Пробный период закончился',
  bannerTrialEndedSub: 'Вернитесь к Pro в пару касаний',
  bannerCta: 'Далее',

  proBadge: 'Pro',
  freeBadge: 'Бесплатно',
  trialBadge: 'Подарок',
  trialTitle: 'Pro в подарок',
  trialSub: 'Пользуйтесь всем без ограничений до',
  trialEndedBadge: 'Пробный период закончился',
  trialEndedTitle: 'Пробный период закончился',
  trialEndedSub: 'Вы вернулись на бесплатный тариф. Перейти на Pro можно в любой момент.',
  heroFreeTitle: 'Smart Basket Pro',
  heroFreeSub: 'Всё без ограничений, на всех ваших устройствах',
  heroProTitle: 'Ваша подписка активна',
  heroPermanentSub: 'Постоянный Pro, без срока окончания',
  heroActiveUntil: 'Активна до',
  heroRenewsOn: 'Продлится автоматически',
  daysLeft: 'дн. осталось',
  dayLeft: 'Остался 1 день',
  expiresToday: 'Заканчивается сегодня',
  expiringSoon: 'Подписка скоро закончится',
  sourceStore: 'Оформлена через магазин приложений',
  sourceGranted: 'Активирована нашей командой',

  compareTitle: 'Что включено в каждый тариф',
  compareFree: 'Бесплатно',
  comparePro: 'Pro',
  compareLists: 'Списков в собственности',
  compareGroups: 'Участников в группе',
  compareAi: 'Запросов AI в день',
  comparePriceChecks: 'Сравнений цен в день',
  compareUnlimited: 'Без ограничений',
  usageResets: 'Счётчики обнуляются каждый день',

  appOnlyTitle: 'Оформите Pro в приложении',
  appOnlyBody: 'Оплата безопасно проходит через App Store или Google Play. Скачайте Smart Basket, войдите в тот же аккаунт, и Pro будет работать на всех устройствах, включая этот сайт.',
  appOnlySoon: 'Приложение скоро появится в магазинах.',
  appOnlyRenewTitle: 'Продлить подписку можно в приложении',
  storeManageTitle: 'Подписка управляется магазином',
  storeManageBody: 'Чтобы изменить или отменить её, откройте настройки подписок App Store или Google Play на телефоне.',
  supportPrompt: 'Вопросы о подписке?',
  supportCta: 'Напишите нам',
};

const DICTS: Record<Language, SubscriptionStrings> = { he, en, ru };

export const getSubscriptionStrings = (lang: Language): SubscriptionStrings => DICTS[lang] ?? he;
