import type { Language } from '../../global/types';

// טקסטים של עמוד "סרוק ובדוק איפה הכי זול". מילון מקומי לפיצ'ר, שלוש השפות
// חייבות להכיל אותם מפתחות (נאכף בטיפוס).
const he = {
  title: 'איפה הכי זול?',
  back: 'חזרה',
  idleTitle: 'סרקו ברקוד של מוצר',
  idleBody: 'נראה לכם באיזה סניף קרוב הוא הכי זול, ואיפה הכי זול בכל הארץ.',
  scan: 'סריקת מוצר',
  scanAnother: 'סריקת מוצר נוסף',
  typeManually: 'הקלדת מספר ברקוד',
  scannerDesc: 'כוונו את המצלמה לברקוד שעל המוצר, ונראה לכם איפה הוא הכי זול.',
  manualPlaceholder: 'מספר ברקוד',
  manualSubmit: 'בדיקה',
  manualInvalid: 'ברקוד הוא 6 עד 14 ספרות',
  nearbyTitle: 'קרוב אליך',
  bestNearTitle: 'הכי זול קרוב אליך',
  bestNationTitle: 'הכי זול בכל הארץ',
  saveUpTo: (amount: string) => `חוסכים עד ${amount} לעומת הסניף היקר באזור`,
  navigate: 'ניווט',
  locationPrompt: 'אפשרו מיקום כדי לראות את הסניפים הזולים בסביבה שלכם.',
  locationPromptIdle: 'אפשרו מיקום מראש, ונראה מיד גם מה הכי זול קרוב אליכם.',
  locationBlocked: 'הגישה למיקום חסומה. אפשר לאשר אותה בהגדרות הדפדפן או המכשיר.',
  locationOn: 'מיקום פעיל: נציג גם סניפים קרובים',
  locating: 'מאתרים את המיקום המדויק שלך...',
  enableLocation: 'הצגת סניפים קרובים',
  noneNearby: (km: number) => `לא מצאנו את המוצר בסניפים בטווח ${km} ק"מ ממך.`,
  km: (d: number) => `${d} ק"מ`,
  meters: (m: number) => `${m} מ'`,
  chainPrice: 'מחיר ברשת',
  chainPriceHint: 'מחיר ברשת, לא אומת לסניף הזה',
  branchPrice: 'מחיר הסניף',
  sortCheapest: 'הכי זול',
  sortClosest: 'הכי קרוב',
  showMore: (n: number) => `עוד ${n} סניפים`,
  showLess: 'הצג פחות',
  cheapestTitle: 'הכי זול בכל הארץ',
  chainsTitle: 'מחיר בכל רשת',
  chainsNote: 'המחיר שרוב סניפי הרשת גובים.',
  disclaimer: 'מחירי מדף ומבצעים שהרשתות מפרסמות לפי חוק שקיפות המחירים. מבצעי מועדון מסומנים ולא נכללים בחישוב.',
  notFoundTitle: 'המוצר לא נמצא',
  notFoundBody: 'אין לנו מחירים לברקוד הזה ברשתות שאנחנו עוקבים אחריהן.',
  error: 'לא הצלחנו לבדוק את המחירים',
  timeout: 'הבדיקה לקחה יותר מדי זמן. בדקו את החיבור ונסו שוב.',
  retry: 'נסו שוב',
  recentTitle: 'נסרקו לאחרונה',
  clearRecent: 'ניקוי',
  from: 'החל מ-',
  // הסניף שהמשתמש נמצא בו
  hereTitle: 'אתם נמצאים כאן',
  hereNoPrice: (chain: string) => `אין לנו מחיר למוצר הזה ב${chain}.`,
  hereIsCheapest: 'זה המחיר הזול ביותר באזור',
  hereCheaperNearby: (chain: string, price: string, save: string) => `קרוב אליך ב${chain}: ${price} (חוסכים ${save})`,
  // מבצעים
  promo: (qty: number, price: string) => (qty > 1 ? `${qty} ב-${price}` : `מבצע ${price}`),
  promoClub: 'למועדון',
  promoSomeBranches: 'בחלק מהסניפים',
  // הכי זול בארץ והרשתות
  nationMostBranches: (chain: string) => `ברוב סניפי ${chain}`,
  nationSingleBranch: (chain: string, typical: string) => `מחיר מיוחד בסניף הזה בלבד. ברוב סניפי ${chain}: ${typical}`,
  chainFromBranch: (price: string, branch: string) => `מ-${price} בסניף ${branch}`,
  chainFromSome: (price: string) => `מ-${price} בחלק מהסניפים`,
  brandOf: (parent: string) => `מסניפי ${parent}`,
  chainStale: (date: string) => `לא עודכן מאז ${date}`,
  pricesUpdated: (when: string) => `המחירים עודכנו ${when}`,
  chainUpdated: (when: string) => `עודכן ${when}`,
  staleBanner: (date: string) => `המחירים עודכנו לאחרונה ב-${date}. ייתכן שחלקם השתנו מאז.`,
  refreshing: 'מעדכנים לפי המיקום המדויק שלך...',
  // טעינה
  loadingSteps: ['מזהים את המוצר...', 'בודקים מחירים בכל הרשתות...', 'מחפשים סניפים קרובים...', 'משווים מחירים ומבצעים...'],
  loadingSlowTitle: 'עוד רגע...',
  lowestFound: 'הכי זול בארץ',
  loadingSlow: 'לוקח יותר זמן מהרגיל. אפשר לחכות או לבטל.',
  cancel: 'ביטול',
  // תוצאה: הכי זול בארץ, ואז המומלץ קרוב אליך
  saveVsPriciest: (amount: string, chain: string) => `חוסכים ${amount} לעומת ${chain}`,
  recommendedTitle: 'מומלץ קרוב אליך',
  recommendedWhy: 'הכי זול בסניפים הקרובים',
  sameAsNation: 'זה המחיר הזול בארץ, ממש קרוב אליך',
  aboveNation: (diff: string) => `רק ${diff} יותר מהזול בארץ`,
  otherNearbyTitle: 'עוד סניפים קרובים',
  cheapestBadge: 'הכי זול',
  promoPerUnit: (unit: string) => `${unit} ליחידה`,
  loadingTitle: 'מחפשים לכם את המחיר הכי טוב',
};

type PriceScanStrings = typeof he;

const en: PriceScanStrings = {
  title: 'Where is it cheapest?',
  back: 'Back',
  idleTitle: 'Scan a product barcode',
  idleBody: 'We will show you the cheapest store near you, and the cheapest price in the country.',
  scan: 'Scan product',
  scanAnother: 'Scan another product',
  typeManually: 'Type a barcode number',
  scannerDesc: 'Point the camera at the barcode on the product, and we will show you where it is cheapest.',
  manualPlaceholder: 'Barcode number',
  manualSubmit: 'Check',
  manualInvalid: 'A barcode has 6 to 14 digits',
  nearbyTitle: 'Near you',
  bestNearTitle: 'Cheapest near you',
  bestNationTitle: 'Cheapest in the country',
  saveUpTo: (amount: string) => `Save up to ${amount} compared to the priciest store nearby`,
  navigate: 'Navigate',
  locationPrompt: 'Allow location to see the cheapest stores around you.',
  locationPromptIdle: 'Allow location now, and we will also show what is cheapest near you right away.',
  locationBlocked: 'Location access is blocked. You can allow it in your browser or device settings.',
  locationOn: 'Location on: nearby stores will be shown',
  locating: 'Finding your exact location...',
  enableLocation: 'Show nearby stores',
  noneNearby: (km: number) => `We did not find this product in stores within ${km} km of you.`,
  km: (d: number) => `${d} km`,
  meters: (m: number) => `${m} m`,
  chainPrice: 'Chain price',
  chainPriceHint: 'Chain price, not verified for this store',
  branchPrice: 'Store price',
  sortCheapest: 'Cheapest',
  sortClosest: 'Closest',
  showMore: (n: number) => `${n} more stores`,
  showLess: 'Show less',
  cheapestTitle: 'Cheapest in the country',
  chainsTitle: 'Price per chain',
  chainsNote: 'The price most stores of the chain charge.',
  disclaimer: 'Shelf prices and promotions published by the chains under the price transparency law. Club promotions are marked and not included in totals.',
  notFoundTitle: 'Product not found',
  notFoundBody: 'We have no prices for this barcode in the chains we track.',
  error: 'Could not check prices',
  timeout: 'The check took too long. Check your connection and try again.',
  retry: 'Try again',
  recentTitle: 'Recently scanned',
  clearRecent: 'Clear',
  from: 'from ',
  hereTitle: 'You are here',
  hereNoPrice: (chain: string) => `We have no price for this product at ${chain}.`,
  hereIsCheapest: 'This is the cheapest price in the area',
  hereCheaperNearby: (chain: string, price: string, save: string) => `Nearby at ${chain}: ${price} (save ${save})`,
  promo: (qty: number, price: string) => (qty > 1 ? `${qty} for ${price}` : `Deal ${price}`),
  promoClub: 'Club',
  promoSomeBranches: 'At some stores',
  nationMostBranches: (chain: string) => `At most ${chain} stores`,
  nationSingleBranch: (chain: string, typical: string) => `Special price at this store only. At most ${chain} stores: ${typical}`,
  chainFromBranch: (price: string, branch: string) => `From ${price} at ${branch}`,
  chainFromSome: (price: string) => `From ${price} at some stores`,
  brandOf: (parent: string) => `Part of ${parent}`,
  chainStale: (date: string) => `Not updated since ${date}`,
  pricesUpdated: (when: string) => `Prices updated ${when}`,
  chainUpdated: (when: string) => `Updated ${when}`,
  staleBanner: (date: string) => `Prices were last updated on ${date}. Some may have changed since.`,
  refreshing: 'Updating for your exact location...',
  loadingSteps: ['Identifying the product...', 'Checking prices in all chains...', 'Finding nearby branches...', 'Comparing prices and deals...'],
  loadingSlowTitle: 'Almost there...',
  lowestFound: 'Lowest in Israel',
  loadingSlow: 'This is taking longer than usual. You can wait or cancel.',
  cancel: 'Cancel',
  saveVsPriciest: (amount: string, chain: string) => `Save ${amount} compared to ${chain}`,
  recommendedTitle: 'Recommended near you',
  recommendedWhy: 'Cheapest at the stores near you',
  sameAsNation: 'The lowest price in the country, right near you',
  aboveNation: (diff: string) => `Only ${diff} more than the lowest in the country`,
  otherNearbyTitle: 'More stores near you',
  cheapestBadge: 'Cheapest',
  promoPerUnit: (unit: string) => `${unit} per unit`,
  loadingTitle: 'Finding you the best price',
};

const ru: PriceScanStrings = {
  title: 'Где дешевле всего?',
  back: 'Назад',
  idleTitle: 'Отсканируйте штрихкод товара',
  idleBody: 'Покажем, в каком магазине рядом он дешевле всего, и самую низкую цену по стране.',
  scan: 'Сканировать товар',
  scanAnother: 'Сканировать ещё товар',
  typeManually: 'Ввести номер штрихкода',
  scannerDesc: 'Наведите камеру на штрихкод товара, и мы покажем, где он дешевле всего.',
  manualPlaceholder: 'Номер штрихкода',
  manualSubmit: 'Проверить',
  manualInvalid: 'Штрихкод содержит от 6 до 14 цифр',
  nearbyTitle: 'Рядом с вами',
  bestNearTitle: 'Дешевле всего рядом с вами',
  bestNationTitle: 'Дешевле всего по стране',
  saveUpTo: (amount: string) => `Экономия до ${amount} по сравнению с самым дорогим магазином рядом`,
  navigate: 'Маршрут',
  locationPrompt: 'Разрешите геолокацию, чтобы увидеть самые дешёвые магазины поблизости.',
  locationPromptIdle: 'Разрешите геолокацию заранее, и мы сразу покажем, где дешевле рядом с вами.',
  locationBlocked: 'Доступ к геолокации заблокирован. Его можно разрешить в настройках браузера или устройства.',
  locationOn: 'Геолокация включена: покажем магазины рядом',
  locating: 'Определяем ваше точное местоположение...',
  enableLocation: 'Показать магазины рядом',
  noneNearby: (km: number) => `Мы не нашли этот товар в магазинах в радиусе ${km} км от вас.`,
  km: (d: number) => `${d} км`,
  meters: (m: number) => `${m} м`,
  chainPrice: 'Цена сети',
  chainPriceHint: 'Цена сети, не проверена для этого магазина',
  branchPrice: 'Цена магазина',
  sortCheapest: 'Дешевле',
  sortClosest: 'Ближе',
  showMore: (n: number) => `Ещё ${n} магазинов`,
  showLess: 'Свернуть',
  cheapestTitle: 'Дешевле всего по стране',
  chainsTitle: 'Цена в каждой сети',
  chainsNote: 'Цена, которую берут большинство магазинов сети.',
  disclaimer: 'Цены на полках и акции, опубликованные сетями по закону о прозрачности цен. Клубные акции отмечены и не входят в расчёт.',
  notFoundTitle: 'Товар не найден',
  notFoundBody: 'У нас нет цен на этот штрихкод в отслеживаемых сетях.',
  error: 'Не удалось проверить цены',
  timeout: 'Проверка заняла слишком много времени. Проверьте подключение и попробуйте снова.',
  retry: 'Повторить',
  recentTitle: 'Недавно отсканированные',
  clearRecent: 'Очистить',
  from: 'от ',
  hereTitle: 'Вы находитесь здесь',
  hereNoPrice: (chain: string) => `У нас нет цены на этот товар в ${chain}.`,
  hereIsCheapest: 'Это самая низкая цена поблизости',
  hereCheaperNearby: (chain: string, price: string, save: string) => `Рядом в ${chain}: ${price} (экономия ${save})`,
  promo: (qty: number, price: string) => (qty > 1 ? `${qty} за ${price}` : `Акция ${price}`),
  promoClub: 'Клуб',
  promoSomeBranches: 'В части магазинов',
  nationMostBranches: (chain: string) => `В большинстве магазинов ${chain}`,
  nationSingleBranch: (chain: string, typical: string) => `Особая цена только в этом магазине. В большинстве магазинов ${chain}: ${typical}`,
  chainFromBranch: (price: string, branch: string) => `От ${price} в магазине ${branch}`,
  chainFromSome: (price: string) => `От ${price} в части магазинов`,
  brandOf: (parent: string) => `Входит в ${parent}`,
  chainStale: (date: string) => `Не обновлялось с ${date}`,
  pricesUpdated: (when: string) => `Цены обновлены ${when}`,
  chainUpdated: (when: string) => `Обновлено ${when}`,
  staleBanner: (date: string) => `Цены последний раз обновлялись ${date}. Некоторые могли измениться.`,
  refreshing: 'Обновляем по вашему точному местоположению...',
  loadingSteps: ['Определяем товар...', 'Проверяем цены во всех сетях...', 'Ищем ближайшие магазины...', 'Сравниваем цены и акции...'],
  loadingSlowTitle: 'Ещё немного...',
  lowestFound: 'Дешевле всего',
  loadingSlow: 'Это занимает больше времени, чем обычно. Можно подождать или отменить.',
  cancel: 'Отмена',
  saveVsPriciest: (amount: string, chain: string) => `Экономия ${amount} по сравнению с ${chain}`,
  recommendedTitle: 'Рекомендуем рядом с вами',
  recommendedWhy: 'Дешевле всего в магазинах рядом',
  sameAsNation: 'Самая низкая цена в стране, совсем рядом',
  aboveNation: (diff: string) => `Всего на ${diff} дороже самой низкой цены в стране`,
  otherNearbyTitle: 'Другие магазины рядом',
  cheapestBadge: 'Дешевле всего',
  promoPerUnit: (unit: string) => `${unit} за штуку`,
  loadingTitle: 'Ищем для вас лучшую цену',
};

const DICTS: Record<Language, PriceScanStrings> = { he, en, ru };

export type { PriceScanStrings };
export const getPriceScanStrings = (lang: Language): PriceScanStrings => DICTS[lang] ?? he;
