import type { Language } from '../../global/types';

// טקסטים של עמוד "סרוק ובדוק איפה הכי זול". מילון מקומי לפיצ'ר, שלוש השפות
// חייבות להכיל אותם מפתחות (נאכף בטיפוס).
const he = {
  title: 'איפה הכי זול?',
  back: 'חזרה',
  idleTitle: 'סרקו ברקוד של מוצר',
  idleBody: 'נראה לכם באיזה סניף קרוב הוא הכי זול, ואיפה הכי זול בכל הארץ.',
  scan: 'סריקת מוצר',
  scanAnother: 'סריקת מוצר נוסף',
  orType: 'או הקלידו את המספר שמתחת לברקוד',
  manualPlaceholder: 'מספר ברקוד',
  manualSubmit: 'בדיקה',
  manualInvalid: 'ברקוד הוא 6 עד 14 ספרות',
  nearbyTitle: 'קרוב אליך',
  bestNearTitle: 'הכי זול קרוב אליך',
  bestNationTitle: 'הכי זול בכל הארץ',
  saveUpTo: (amount: string) => `חוסכים עד ${amount} לעומת הסניף היקר באזור`,
  navigate: 'ניווט',
  locationPrompt: 'אפשרו מיקום כדי לראות את הסניפים הזולים בסביבה שלכם.',
  locationPromptIdle: 'אפשרו מיקום מראש, ונראה מיד גם מה הכי זול קרוב אליכם.',
  locationBlocked: 'הגישה למיקום חסומה. אפשר לאשר אותה בהגדרות הדפדפן או המכשיר.',
  locationOn: 'מיקום פעיל: נציג גם סניפים קרובים',
  enableLocation: 'הצגת סניפים קרובים',
  noneNearby: (km: number) => `לא מצאנו את המוצר בסניפים בטווח ${km} ק"מ ממך.`,
  km: (d: number) => `${d} ק"מ`,
  chainPrice: 'מחיר ברשת',
  sortCheapest: 'הכי זול',
  sortClosest: 'הכי קרוב',
  showMore: (n: number) => `עוד ${n} סניפים`,
  showLess: 'הצג פחות',
  cheapestTitle: 'הכי זול בכל הארץ',
  chainsTitle: 'מחיר בכל רשת',
  chainsNote: 'המחיר שרוב סניפי הרשת גובים.',
  disclaimer: 'מחירי מדף שהרשתות מפרסמות. מבצעים ומחירי מועדון לא נכללים.',
  notFoundTitle: 'המוצר לא נמצא',
  notFoundBody: 'אין לנו מחירים לברקוד הזה ברשתות שאנחנו עוקבים אחריהן.',
  error: 'לא הצלחנו לבדוק את המחירים',
  retry: 'נסו שוב',
  recentTitle: 'נסרקו לאחרונה',
  clearRecent: 'ניקוי',
  from: 'החל מ-',
};

type PriceScanStrings = typeof he;

const en: PriceScanStrings = {
  title: 'Where is it cheapest?',
  back: 'Back',
  idleTitle: 'Scan a product barcode',
  idleBody: 'We will show you the cheapest store near you, and the cheapest price in the country.',
  scan: 'Scan product',
  scanAnother: 'Scan another product',
  orType: 'or type the number under the barcode',
  manualPlaceholder: 'Barcode number',
  manualSubmit: 'Check',
  manualInvalid: 'A barcode has 6 to 14 digits',
  nearbyTitle: 'Near you',
  bestNearTitle: 'Cheapest near you',
  bestNationTitle: 'Cheapest in the country',
  saveUpTo: (amount: string) => `Save up to ${amount} compared to the priciest store nearby`,
  navigate: 'Navigate',
  locationPrompt: 'Allow location to see the cheapest stores around you.',
  locationPromptIdle: 'Allow location now, and we will also show what is cheapest near you right away.',
  locationBlocked: 'Location access is blocked. You can allow it in your browser or device settings.',
  locationOn: 'Location on: nearby stores will be shown',
  enableLocation: 'Show nearby stores',
  noneNearby: (km: number) => `We did not find this product in stores within ${km} km of you.`,
  km: (d: number) => `${d} km`,
  chainPrice: 'Chain price',
  sortCheapest: 'Cheapest',
  sortClosest: 'Closest',
  showMore: (n: number) => `${n} more stores`,
  showLess: 'Show less',
  cheapestTitle: 'Cheapest in the country',
  chainsTitle: 'Price per chain',
  chainsNote: 'The price most stores of the chain charge.',
  disclaimer: 'Shelf prices published by the chains. Promotions and club prices are not included.',
  notFoundTitle: 'Product not found',
  notFoundBody: 'We have no prices for this barcode in the chains we track.',
  error: 'Could not check prices',
  retry: 'Try again',
  recentTitle: 'Recently scanned',
  clearRecent: 'Clear',
  from: 'from ',
};

const ru: PriceScanStrings = {
  title: 'Где дешевле всего?',
  back: 'Назад',
  idleTitle: 'Отсканируйте штрихкод товара',
  idleBody: 'Покажем, в каком магазине рядом он дешевле всего, и самую низкую цену по стране.',
  scan: 'Сканировать товар',
  scanAnother: 'Сканировать ещё товар',
  orType: 'или введите число под штрихкодом',
  manualPlaceholder: 'Номер штрихкода',
  manualSubmit: 'Проверить',
  manualInvalid: 'Штрихкод содержит от 6 до 14 цифр',
  nearbyTitle: 'Рядом с вами',
  bestNearTitle: 'Дешевле всего рядом с вами',
  bestNationTitle: 'Дешевле всего по стране',
  saveUpTo: (amount: string) => `Экономия до ${amount} по сравнению с самым дорогим магазином рядом`,
  navigate: 'Маршрут',
  locationPrompt: 'Разрешите геолокацию, чтобы увидеть самые дешёвые магазины поблизости.',
  locationPromptIdle: 'Разрешите геолокацию заранее, и мы сразу покажем, где дешевле рядом с вами.',
  locationBlocked: 'Доступ к геолокации заблокирован. Его можно разрешить в настройках браузера или устройства.',
  locationOn: 'Геолокация включена: покажем магазины рядом',
  enableLocation: 'Показать магазины рядом',
  noneNearby: (km: number) => `Мы не нашли этот товар в магазинах в радиусе ${km} км от вас.`,
  km: (d: number) => `${d} км`,
  chainPrice: 'Цена сети',
  sortCheapest: 'Дешевле',
  sortClosest: 'Ближе',
  showMore: (n: number) => `Ещё ${n} магазинов`,
  showLess: 'Свернуть',
  cheapestTitle: 'Дешевле всего по стране',
  chainsTitle: 'Цена в каждой сети',
  chainsNote: 'Цена, которую берут большинство магазинов сети.',
  disclaimer: 'Цены на полках, опубликованные сетями. Акции и клубные цены не учитываются.',
  notFoundTitle: 'Товар не найден',
  notFoundBody: 'У нас нет цен на этот штрихкод в отслеживаемых сетях.',
  error: 'Не удалось проверить цены',
  retry: 'Повторить',
  recentTitle: 'Недавно отсканированные',
  clearRecent: 'Очистить',
  from: 'от ',
};

const DICTS: Record<Language, PriceScanStrings> = { he, en, ru };

export type { PriceScanStrings };
export const getPriceScanStrings = (lang: Language): PriceScanStrings => DICTS[lang] ?? he;
